
import localFont from "next/font/local";
// import "./globals.css";
import "../styles/app.scss";
import 'bootstrap/dist/css/bootstrap.min.css';
import StoreProvider from "@/redux/StoreProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Mera Driver",
  description: "Generated by create next app",
};

    // Client-side code her

if (typeof document !== 'undefined') {
  // Client-side code
  const element = document.querySelector('#my-element');
}



if (typeof window !== 'undefined') {
  import('bootstrap/dist/js/bootstrap.bundle.min.js');
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
